<?php
/*DEFINE('DB_HOST','localhost');
//DEFINE('DB_PORT','22');
DEFINE('DB_USER','root');
DEFINE('DB_PASSWD','autumn');
DEFINE('DB_DATABASE','postdata92021');
*/
DEFINE('DB_HOST','localhost');
//DEFINE('DB_PORT','22');
DEFINE('DB_USER','prj2021blancapaula');
DEFINE('DB_PASSWD','5NCkj8wv');
DEFINE('DB_DATABASE','prj2021blancapaula');
?>
